providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview -- --host 0.0.0.0 --port 3000"
